---
install-dev:
    tags: [dev-utils]
    stage: install
    before_script:
        - cargo --version
        
    script: 
        - cargo build --release
        - cp target/release/poppy /usr/bin/
        - cp target/release/poppy .
        - poppy --version
    artifacts:
        paths: 
            - poppy


stages:
    - install
    
