---
build:
    tags: [dev-utils]
    stage: build
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .cargo
            - target
    before_script:
        - cargo --version
    script:
        - cargo build --release
        - cargo appimage # --target=x86_64-unknown-linux-musl
        - cp target/release/poppy .
    artifacts:
        paths:
            - ./poppy

install-dev:
    tags: [dev-utils]
    stage: install
    needs:
        - job: build
          artifacts: true
    script:
        - cp ./poppy /usr/bin/
        - poppy --version
    artifacts:
        paths: 
            - ./poppy

package:
    tags: [dev-utils]
    stage: package
    needs:
        - job: build
          artifacts: true
    script:
        - tar -czvf poppy.tar.gz poppy
    artifacts:
        paths:
            - ./poppy.tar.gz

push-artifactory:
    tags: [dev-utils]
    stage: push
    needs:
        - job: package
          artifacts: true
    script:
        - chmod +x ./poppup.py
        - ./poppup.py --push --file=./poppy.tar.gz --name=poppy --arch=linux-x64

install-alse-1:
    tags: [alse-first]
    stage: install-runners
    needs:
        - job: push-artifactory
          artifacts: true
    rules:
        - if: $CI_PIPELINE_SOURCE == "trigger-install-alse"
          when: always
        - if: '$CI_COMMIT_TAG'
          when: always
        - when: manual
    before_script:
        - pip3 install requests
    script:
        - python3 poppup.py --install-latest --arch=linux-x64 --where=/local_bin
        - poppy --version

install-alse-2:
    tags: [alse-second]
    stage: install-runners
    rules:
        - if: $CI_PIPELINE_SOURCE == "trigger-install-alse"
          when: always
        - if: '$CI_COMMIT_TAG'
          when: always
        - when: manual
    needs:
        - job: push-artifactory
          artifacts: true
    before_script:
        - pip3 install requests
    script:
        - python3 poppup.py --install-latest --arch=linux-x64 --where=/local_bin
        - poppy --version

stages:
    - build
    - install
    - package
    - push
    - install-runners
    
