---
install-dev:
    tags: [dev-utils]
    stage: install
    before_script:
        - cargo --version
        
    script: 
        - cargo build --release
        - cp target/release/poppy /usr/bin/
        - poppy --version

stages:
    - install
    
