variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_DEPTH: 100
    PKG_VER: 0.0.0

include:
    - local: /.gitlab/build.yml
    - local: /.gitlab/test.yml
    - local: /.gitlab/package.yml
    - local: /.gitlab/deploy.yml
    - local: /.gitlab/release.yml

stages:
    - build
    - test
    - package
    - deploy
    - release
    
