---
build:
    tags: [dev-utils]
    stage: build
    before_script:
        - cargo --version
    script:
        - cargo build --release
        - cp target/release/poppy .
    artifacts:
        paths:
            - ./poppy

install-dev:
    tags: [dev-utils]
    stage: install
    needs:
        - job: build
          artifacts: true
    script:
        - cp ./poppy /usr/bin/
        - poppy --version
    artifacts:
        paths: 
            - ./poppy

stages:
    - build
    - install
    - package
    
