---
install-dev:
    tags: [dev-utils]
    rules:
        - when: manual
    stage: install
    before_script:
        - whereis cargo
        - cargo --version
        - ls -la /usr/bin/cargo
        
    script: 
        - cargo build --release
        - cp target/release/poppy /usr/bin/
        - poppy --version

stages:
    - install
    
