---
deploy arch x64:
  tags: [dev-utils]
  stage: deploy
  needs:
    - job: package arch x64
      artifacts: true
  script:
    - find . -maxdepth 1 -name "*.pkg.tar.zst" -exec curl --form file=@{} http://213.170.107.251/pacman-upload \; 
